dist: trusty
sudo: false
language: cpp

matrix:
  include:
    # g++-7
    # thank you to Drag-On from stackoverflow
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - libpng-dev
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LINKER_FLAGS=""

    #clang-6
    - os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
          - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
          - clang-6.0
          - libstdc++6
          - libpng-dev
      env:
      - MATRIX_EVAL="CC=clang-6.0 && CXX=clang-6.0"
      - LINKER_FLAGS="-stdlib=libc++ -lc++abi"
before_install:
  - sudo add-apt-repository -y ppa:samuel-bachmann/boost
  - sudo apt-get -y -d update
  - eval "${MATRIX_EVAL}"
install:
  - sudo apt-get -y install cmake3 libboost-test1.60-dev libboost-date-time1.60-dev
script:
  - bin/fetch-configlet
  - bin/configlet lint .
  - cmake -G "Unix Makefiles"
  - make
